<a href="https://colab.research.google.com/github/Ankam123niteesh/2303A52341_SML/blob/main/2303A52341_SML_A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ASSIGNMENT-4
Question 1:

https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification?select=train.csvLinks to an external site.

From the above data:

Read the data with pandas and find features and target variables
Normalize the data with min-max scaling
Split the data into train and test.

In [15]:
import pandas as pd
data=pd.read_csv("/content/train.csv")
print(data)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [2]:
y=data['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
x=data.drop('price_range',axis=1)
x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [19]:
new=data-x.min()/x.max()-x.min()
new

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,price_range,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,340.749249,0.0,1.533333,0.0,1.0,0.0,4.96875,0.4,107.6,0.875,...,NaN,20.0,255.74975,2292.935968,3.736842,7.0,16.9,0.0,0.0,1.0
1,519.749249,1.0,-0.166667,1.0,0.0,1.0,50.96875,0.5,55.6,1.875,...,NaN,905.0,1487.74975,2374.935968,11.736842,3.0,4.9,1.0,1.0,0.0
2,61.749249,1.0,-0.166667,1.0,2.0,1.0,38.96875,0.7,64.6,3.875,...,NaN,1263.0,1215.74975,2346.935968,5.736842,2.0,6.9,1.0,1.0,0.0
3,113.749249,1.0,1.833333,0.0,0.0,0.0,7.96875,0.6,50.6,4.875,...,NaN,1216.0,1285.74975,2512.935968,10.736842,8.0,8.9,1.0,0.0,0.0
4,1319.749249,1.0,0.533333,0.0,13.0,1.0,41.96875,0.4,60.6,0.875,...,NaN,1208.0,711.74975,1154.935968,2.736842,2.0,12.9,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,292.749249,1.0,-0.166667,1.0,0.0,1.0,-0.03125,0.6,25.6,4.875,...,NaN,1222.0,1389.74975,411.935968,7.736842,4.0,16.9,1.0,1.0,0.0
1996,1463.749249,1.0,1.933333,1.0,0.0,0.0,36.96875,0.0,106.6,2.875,...,NaN,915.0,1464.74975,1775.935968,5.736842,10.0,13.9,1.0,1.0,1.0
1997,1409.749249,0.0,0.233333,1.0,1.0,1.0,33.96875,0.5,27.6,6.875,...,NaN,868.0,1131.74975,2800.935968,3.736842,1.0,2.9,1.0,1.0,0.0
1998,1010.749249,0.0,0.233333,0.0,4.0,1.0,43.96875,-0.1,64.6,3.875,...,NaN,336.0,169.74975,612.935968,12.736842,10.0,16.9,1.0,1.0,1.0
1999,8.749249,1.0,1.333333,1.0,5.0,1.0,42.96875,0.7,87.6,4.875,...,NaN,483.0,253.74975,3662.935968,13.736842,4.0,-0.1,1.0,1.0,1.0

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(new,y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1572     393.749249   0.0    -0.166667       1.0   6.0     0.0    13.96875
1442     471.749249   0.0    -0.166667       1.0   5.0     0.0    50.96875
1516     579.749249   1.0     1.233333       1.0  13.0     1.0    39.96875
259     1057.749249   1.0     0.933333       1.0   6.0     1.0     3.96875
945      330.749249   0.0     0.433333       0.0   0.0     1.0    43.96875
...             ...   ...          ...       ...   ...     ...         ...
500      776.749249   1.0    -0.166667       1.0   1.0     0.0    51.96875
1837     481.749249   0.0    -0.066667       1.0   0.0     1.0    42.96875
941      241.749249   0.0    -0.166667       1.0   0.0     1.0    30.96875
421      676.749249   0.0     1.533333       1.0   6.0     0.0    54.96875
1829     563.749249   0.0     1.033333       1.0   4.0     1.0    45.96875

      m_dep  mobile_wt  n_cores  ...  price_range  px_height    px_width  \
1572    0.1       83.6    6.875  ...          NaN      126.0  1074.74975
1442    0.3      115.6    3.875  ...          NaN      105.0    87.74975
1516   -0.1       20.6    5.875  ...          NaN       83.0   315.74975
259     0.3       81.6    4.875  ...          NaN      179.0  1058.74975
945     0.1       12.6    4.875  ...          NaN      820.0   865.74975
...     ...        ...      ...  ...          ...        ...         ...
500    -0.1       23.6    6.875  ...          NaN      581.0   249.74975
1837   -0.1       49.6    2.875  ...          NaN      948.0   704.74975
941     0.1       14.6    0.875  ...          NaN     1587.0  1158.74975
421     0.1        3.6    1.875  ...          NaN       96.0   851.74975
1829    0.1       81.6    4.875  ...          NaN     1188.0  1447.74975

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1572  2865.935968   1.736842   0.0        1.9      0.0           0.0   1.0
1442  1604.935968   7.736842  10.0       13.9      0.0           1.0   0.0
1516  2199.935968   1.736842   4.0        4.9      1.0           0.0   0.0
259   3095.935968   3.736842   1.0        0.9      1.0           1.0   1.0
945   3060.935968   2.736842   0.0       16.9      1.0           1.0   0.0
...           ...        ...   ...        ...      ...           ...   ...
500    898.935968   1.736842   1.0       17.9      0.0           0.0   1.0
1837  1795.935968  -0.263158   3.0        3.9      1.0           0.0   1.0
941     59.935968  13.736842  10.0        1.9      1.0           0.0   0.0
421   2235.935968  10.736842  14.0        7.9      1.0           1.0   0.0
1829     8.935968   2.736842   0.0        9.9      1.0           0.0   0.0

[1600 rows x 21 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1856    1284.749249   0.0     1.933333       0.0   6.0     0.0    11.96875
364      414.749249   1.0     1.933333       0.0   0.0     0.0    33.96875
1948     246.749249   0.0     0.733333       0.0   0.0     0.0    22.96875
1458     866.749249   0.0    -0.166667       0.0  10.0     1.0    39.96875
609      710.749249   0.0     1.933333       0.0   1.0     1.0    43.96875
...             ...   ...          ...       ...   ...     ...         ...
1163    1428.749249   1.0     1.333333       0.0  11.0     0.0    13.96875
572     1199.749249   1.0    -0.166667       0.0  13.0     1.0    43.96875
1105    1008.749249   1.0     1.833333       1.0  11.0     0.0    44.96875
1903     859.749249   1.0     0.733333       0.0   1.0     0.0    44.96875
481     1195.749249   1.0     0.033333       0.0   1.0     1.0    31.96875

      m_dep  mobile_wt  n_cores  ...  price_range  px_height    px_width  \
1856    0.8       34.6    2.875  ...          NaN      616.0   411.74975
364     0.1      114.6    2.875  ...          NaN      188.0   491.74975
1948    0.8       29.6    5.875  ...          NaN       88.0   208.74975
1458    0.0       10.6   -0.125  ...          NaN      907.0   424.74975
609     0.1       21.6    2.875  ...          NaN      611.0  1214.74975
...     ...        ...      ...  ...          ...        ...         ...
1163    0.6      105.6    6.875  ...          NaN     1901.0  1419.74975
572     0.7       34.6    0.875  ...          NaN      364.0   327.74975
1105    0.5       57.6    0.875  ...          NaN      118.0   669.74975
1903    0.8       88.6    3.875  ...          NaN      881.0   881.74975
481    -0.1       14.6   -0.125  ...          NaN      236.0   763.74975

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1856  2781.935968  12.736842   0.0       11.9      1.0           0.0   0.0
364   1213.935968   7.736842   0.0       11.9      0.0           1.0   0.0
1948  1717.935968  11.736842   5.0       10.9      0.0           1.0   1.0
1458  1333.935968   6.736842   0.0       11.9      1.0           0.0   0.0
609   1992.935968   8.736842   3.0        1.9      1.0           1.0   1.0
...           ...        ...   ...        ...      ...           ...   ...
1163  1526.935968  11.736842   3.0       10.9      0.0           0.0   1.0
572   3460.935968   5.736842   0.0        7.9      1.0           1.0   0.0
1105   630.935968  12.736842   6.0        2.9      0.0           0.0   0.0
1903  2238.935968   2.736842   7.0       13.9      0.0           0.0   1.0
481   3444.935968   9.736842   9.0        5.9      1.0           1.0   0.0

[400 rows x 21 columns]
1572    2
1442    1
1516    1
259     3
945     3
       ..
500     0
1837    1
941     0
421     2
1829    0
Name: price_range, Length: 1600, dtype: int64
1856    3
364     0
1948    1
1458    1
609     2
       ..
1163    2
572     3
1105    0
1903    2
481     3
Name: price_range, Length: 400, dtype: int64

Question 2:

Read the data with pandas and describe the data

Find data type and shape of each column

Find the target and features

Find the null values (if yes fill the null values with â€˜0â€™ or mean of that column)

Normalize all the features

Split the data into train and test.

In [26]:
import pandas as pd
data1=pd.read_csv("/content/sample_data/california_housing_train.csv")
print(data1)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [35]:
#DESCRIBE
data1.describe()
data1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [36]:
#SHAPE
shape=data1.shape
print(shape)

(17000, 9)

In [37]:
#TYPE
type=data1.dtypes
type

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [38]:
#TARGET
Y=data1['median_house_value']
Y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [39]:
#FEATURES
X=data1.drop('median_house_value',axis=1)
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250
...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147

In [40]:
null=data1.isnull()
null

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False

In [41]:
normalised=data1-X.min()/X.max()-X.min()
normalised

,households,housing_median_age,latitude,longitude,median_house_value,median_income,population,total_bedrooms,total_rooms
0,470.999836,13.980769,0.874315,8.952169,NaN,0.960374,1011.999916,1281.999845,5609.999947
1,461.999836,17.980769,1.084315,8.792169,NaN,1.286774,1125.999916,1899.999845,7647.999947
2,115.999836,15.980769,0.374315,8.702169,NaN,1.117674,329.999916,172.999845,717.999947
3,224.999836,12.980769,0.324315,8.692169,NaN,2.658474,511.999916,335.999845,1498.999947
4,260.999836,18.980769,0.254315,8.692169,NaN,1.391774,620.999916,324.999845,1451.999947
...,...,...,...,...,...,...,...,...,...
16995,367.999836,50.980769,7.264315,-0.997831,NaN,1.823874,903.999916,392.999845,2214.999947
16996,463.999836,34.980769,7.374315,-1.007831,NaN,1.984674,1190.999916,526.999845,2346.999947
16997,454.999836,15.980769,8.524315,-1.037831,NaN,2.498074,1240.999916,529.999845,2674.999947
16998,476.999836,17.980769,8.484315,-1.037831,NaN,1.446474,1294.999916,550.999845,2669.999947
16999,268.999836,50.980769,7.224315,-1.087831,NaN,2.481474,802.999916,298.999845,1817.999947

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(normalised,Y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

        households  housing_median_age  latitude  longitude  \
7303    295.999836           46.980769  0.674315   4.922169
12831   408.999836           17.980769  3.914315   1.452169
13976   240.999836           27.980769  4.354315   1.222169
3268    550.999836           28.980769  0.414315   5.402169
7206    171.999836           45.980769  0.684315   4.932169
...            ...                 ...       ...        ...
500    1289.999836           18.980769 -0.485685   6.272169
12077   169.999836           34.980769  5.864315   1.832169
15277   216.999836           50.980769  4.564315   0.982169
4517    295.999836           14.980769  0.444315   5.222169
5925   1104.999836           45.980769  0.784315   5.052169

       median_house_value  median_income   population  total_bedrooms  \
7303                  NaN       4.279274   915.999916      333.999845
12831                 NaN       5.784574  1493.999916      425.999845
13976                 NaN       5.516874   686.999916      249.999845
3268                  NaN       3.186974  3245.999916      570.999845
7206                  NaN       1.800074   412.999916      185.999845
...                   ...            ...          ...             ...
500                   NaN       2.664674  3683.999916     1324.999845
12077                 NaN       1.633474   500.999916      182.999845
15277                 NaN       3.383474   485.999916      213.999845
4517                  NaN       6.554674   874.999916      261.999845
5925                  NaN       2.504474  3344.999916     1269.999845

       total_rooms
7303   2006.999947
12831  2632.999947
13976  1691.999947
3268   2648.999947
7206    822.999947
...            ...
500    6693.999947
12077  1121.999947
15277  1169.999947
4517   2067.999947
5925   5074.999947

[13600 rows x 9 columns]
       households  housing_median_age  latitude  longitude  \
10914  631.999836            3.980769  4.194315   2.412169
6241   368.999836           35.980769  0.914315   5.012169
5904   604.999836           45.980769  0.474315   5.062169
9578   590.999836           37.980769  3.204315   3.912169
9444   201.999836           32.980769  0.984315   4.012169
...           ...                 ...       ...        ...
12228  242.999836           50.980769  5.234315   1.792169
6639   160.999836           39.980769  0.594315   4.982169
7850   708.999836            8.980769  1.384315   4.862169
4886   296.999836           40.980769  0.694315   5.162169
3618   201.999836           25.980769  0.294315   5.352169

       median_house_value  median_income   population  total_bedrooms  \
10914                 NaN       1.695974  1589.999916      743.999845
6241                  NaN       4.552974   963.999916      366.999845
5904                  NaN       2.480274  1384.999916      624.999845
9578                  NaN       2.111274  2195.999916      606.999845
9444                  NaN       4.349174   441.999916      218.999845
...                   ...            ...          ...             ...
12228                 NaN       1.490974   557.999916      293.999845
6639                  NaN       2.121374   638.999916      131.999845
7850                  NaN       3.760874  2160.999916      812.999845
4886                  NaN       2.896474  1001.999916      296.999845
3618                  NaN       5.386374   431.999916      341.999845

       total_rooms
10914  2896.999947
6241   1951.999947
5904   2546.999947
9578   3024.999947
9444   1186.999947
...            ...
12228  1381.999947
6639    617.999947
7850   4119.999947
4886   1433.999947
3618   1794.999947

[3400 rows x 9 columns]
7303     170500.0
12831    248000.0
13976    254200.0
3268     182100.0
7206     133300.0
           ...
500      154600.0
12077     93800.0
15277    235600.0
4517     338800.0
5925     186800.0
Name: median_house_value, Length: 13600, dtype: float64
10914    127500.0
6241     261300.0
5904     192700.0
9578      62000.0
9444     396400.0
           ...
12228     94600.0
6639     159600.0
7850     151600.0
4886     195800.0
3618     500001.0
Name: median_house_value, Length: 3400, dtype: float64